(()=>{'use strict';
let data=window.HAIFENG_MANUSCRIPT;
if(new URLSearchParams(location.search).get('preview')==='1'){
  try{const d=JSON.parse(sessionStorage.getItem('haifeng-cms-preview-v1')||'null');if(d&&Array.isArray(d.pages)&&d.chapters?.length===50){data=d;const tag=document.createElement('div');tag.className='reader-preview-banner';tag.textContent='編修室試讀｜目前修改僅供本機預覽，尚未公開發布';document.querySelector('.r-top').after(tag)}}catch(e){console.warn('書稿試讀資料無法載入')}
}
if(!data){document.getElementById('readerError').hidden=false;return}
const P=data.pages;let current=0,turning=false,mobile=matchMedia('(max-width:760px)').matches;let scale=1;
const $=x=>document.getElementById(x);const book=$('book'),left=$('leafLeft'),right=$('leafRight'),sheet=$('turnSheet'),front=$('turnFront'),back=$('turnBack'),progress=$('progressBar'),pageNo=$('readerPageNo'),drawer=$('drawer'),veil=$('veil'),search=$('searchQuery'),contents=$('contentsList'),results=$('searchResults'),hits=$('searchHits');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cached=()=>{try{return JSON.parse(localStorage.getItem('haifeng-reader-v1')||'{}')}catch{return {}}};
function save(){try{localStorage.setItem('haifeng-reader-v1',JSON.stringify({page:current+1,scale,updated:new Date().toISOString()}))}catch{}}
function makePage(i){if(i<0||i>=P.length)return '<div class="page-inner"><div class="page-kicker">王家傳 · 海風有名</div></div>';
 const p=P[i];if(i===0)return '<div class="paper-cover"><p class="cover-micro">THE WANG FAMILY CHRONICLES</p><div class="cover-divider"></div><p class="cover-series">第一輯 · 第一代</p><div class="cover-title">海風有名</div><p class="cover-bottom">第二輪校樣　·　二〇二六年十月</p></div>';
 let body='';if(i===2){body='<div class="page-toc-preview"><h2 class="page-chapter">目次｜五十回</h2><p>全書分十部、五十回。點選左上角「章回目次」即可直接跳至任一回；亦可使用左右鍵或下方按鈕翻頁。</p><p><button type="button" class="toc-opener" data-open-toc>展開五十回目次　／　選讀章回</button></p></div>'}
 else {for(const b of p.blocks){const txt=escapeHtml(b.text);switch(b.type){case 'part':body+=`<h3 class="page-part">${txt}</h3>`;break;case 'chapter':body+=`<h2 class="page-chapter">${txt}</h2>`;break;case 'heading':body+=`<h3 class="page-part">${txt}</h3>`;break;case 'p':body+=`<p>${txt}</p>`;break;}}}
 return `<div class="page-inner" aria-label="原稿第 ${p.pdf} 頁"><div class="page-kicker">${escapeHtml(p.section)}　／　${escapeHtml(p.running)}</div><div class="page-content">${body}</div><div class="page-num">— ${p.pdf} —</div></div>`;}
function refresh(){const spread=mobile?current:Math.floor(current/2)*2;left.innerHTML=makePage(spread);if(!mobile)right.innerHTML=makePage(spread+1);let displayStart=spread+1,displayEnd=mobile?spread+1:Math.min(P.length,spread+2);pageNo.textContent=`原稿 ${displayStart}${displayEnd>displayStart?'—'+displayEnd:''} / ${P.length} 頁`;progress.style.width=(100*displayEnd/P.length).toFixed(2)+'%';$('prevButton').disabled=current<=0;$('nextButton').disabled=current+(mobile?1:2)>=P.length;document.documentElement.style.setProperty('--booktype',String(scale));$('currentChapter').textContent=P[Math.min(P.length-1,current)].running;save();}
function turn(delta){if(turning)return;const step=mobile?1:2;let target=delta>0?Math.min(P.length-1,current+step):Math.max(0,current-step);if(target===current)return;const from=mobile?current:Math.floor(current/2)*2;const to=mobile?target:Math.floor(target/2)*2;const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
 if(reduce){current=target;refresh();return}turning=true;sheet.className='turn-sheet';
 if(mobile){front.innerHTML=makePage(from);back.innerHTML=makePage(to);left.innerHTML=makePage(to)}else if(delta>0){front.innerHTML=makePage(from+1);back.innerHTML=makePage(to);right.innerHTML=makePage(to+1)}else{front.innerHTML=makePage(from);back.innerHTML=makePage(to+1);left.innerHTML=makePage(to)}
 sheet.classList.add(delta>0?'go-next':'go-prev');let done=false;const finish=()=>{if(done)return;done=true;sheet.className='turn-sheet';current=target;turning=false;refresh()};sheet.addEventListener('animationend',finish,{once:true});setTimeout(finish,900);
}
function jump(page){if(turning)return;current=Math.max(0,Math.min(P.length-1,page-1));refresh();closeDrawer();book.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});}
function openDrawer(mode){drawer.classList.add('open');veil.classList.add('open');drawer.setAttribute('aria-hidden','false');veil.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setMode(mode||'contents');$('drawerClose').focus();}
function closeDrawer(){drawer.classList.remove('open');veil.classList.remove('open');drawer.setAttribute('aria-hidden','true');veil.setAttribute('aria-hidden','true');document.body.style.overflow='';}
function setMode(mode){const searching=mode==='search';contents.classList.toggle('hidden',searching);results.classList.toggle('active',searching);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(searching)search.focus();}
function renderToc(){let markup='<button class="toc-link" data-jump="4"><span>序</span>序章｜壽宴上的兩種光</button>';data.parts.forEach((part,i)=>{markup+=`<section class="toc-section"><h3>${escapeHtml(part.name)}</h3>`;data.chapters.filter(c=>c.part===i+1).forEach(ch=>{markup+=`<button class="toc-link" data-jump="${ch.page}"><span>${String(ch.index).padStart(2,'0')}</span>${escapeHtml(ch.name)}</button>`});markup+='</section>'});markup+='<section class="toc-section"><h3>附記</h3><button class="toc-link" data-jump="145">史料與創作說明</button><button class="toc-link" data-jump="146">編輯版本與進度</button></section>';contents.innerHTML=markup;}
let searchTimer=null;search.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const q=search.value.trim();if(!q){hits.innerHTML='<p>輸入人物、地名、回目或詞句，尋找原稿中出現的位置。</p>';return}const found=[];P.forEach(p=>{const all=p.blocks.map(b=>b.text).join('');let ix=all.indexOf(q);if(ix!==-1){const snip=all.slice(Math.max(0,ix-24),Math.min(all.length,ix+q.length+48));found.push({page:p.pdf,snip});}});hits.replaceChildren();const top=document.createElement('p');top.textContent=`搜尋「${q}」：找到 ${found.length} 頁` ;hits.append(top);for(const result of found.slice(0,65)){const b=document.createElement('button');b.className='toc-link';b.dataset.jump=result.page;b.innerText=`第 ${result.page} 頁　${result.snip}`;hits.append(b)}},120)});
const old=cached();if(Number.isInteger(old.page))current=Math.max(0,Math.min(P.length-1,old.page-1));if(old.scale&&old.scale>=.84&&old.scale<=1.28)scale=old.scale;
$('prevButton').addEventListener('click',()=>turn(-1));$('nextButton').addEventListener('click',()=>turn(1));$('fontSmaller').addEventListener('click',()=>{scale=Math.max(.86,Math.round((scale-.08)*100)/100);refresh()});$('fontLarger').addEventListener('click',()=>{scale=Math.min(1.24,Math.round((scale+.08)*100)/100);refresh()});$('tocButton').addEventListener('click',()=>openDrawer('contents'));$('findButton').addEventListener('click',()=>openDrawer('search'));$('drawerClose').addEventListener('click',closeDrawer);veil.addEventListener('click',closeDrawer);
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
document.addEventListener('click',e=>{const goto=e.target.closest('[data-jump]');if(goto){jump(+goto.dataset.jump);return}if(e.target.closest('[data-open-toc]'))openDrawer('contents')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer.classList.contains('open')){closeDrawer();return}if(drawer.classList.contains('open')||e.target.matches('input,textarea,select'))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();turn(1)}else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();turn(-1)}});
let startX=0,startY=0;book.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});book.addEventListener('touchend',e=>{if(e.changedTouches.length!==1)return;const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5)turn(dx<0?1:-1)},{passive:true});
const mobileMql=matchMedia('(max-width:760px)');mobileMql.addEventListener('change',e=>{mobile=e.matches;refresh()});
renderToc();refresh();
})();
